- name: Déployer Zabbix Agent
  hosts: infra_home
  become: true
  tasks:
    - name: Installer zabbix-agent2
      apt:
        name: zabbix-agent2
        state: present
        update_cache: yes

    - name: Configurer l'agent
      copy:
        dest: /etc/zabbix/zabbix_agent2.conf
        content: |
          Server=192.168.0.252
          ServerActive=192.168.0.252
          Hostname={{ inventory_hostname }}

    - name: Redémarrer le service
      service:
        name: zabbix-agent2
        state: restarted
        enabled: true

